//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smart_Heating_System
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SmartHeatingSystemEntities : DbContext
    {
        private static SmartHeatingSystemEntities _context;
        public SmartHeatingSystemEntities()
            : base("name=SmartHeatingSystemEntities1")
        {
        }
        public static SmartHeatingSystemEntities GetContext()
        {
            if (_context == null)
                _context = new SmartHeatingSystemEntities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Отопление> Отопление { get; set; }
        public virtual DbSet<Пользователь> Пользователь { get; set; }
        public virtual DbSet<Помещение> Помещение { get; set; }
        public virtual DbSet<Статистика> Статистика { get; set; }
        public virtual DbSet<Устройства> Устройства { get; set; }
        public virtual DbSet<УстройстваПомещения> УстройстваПомещения { get; set; }
    }
}
