//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smart_Heating_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Статистика
    {
        public int ID { get; set; }
        public Nullable<int> Устройство { get; set; }
        public Nullable<int> СтатТемпературы { get; set; }
        public Nullable<int> СтатВоды { get; set; }
        public Nullable<int> СтатЭнергии { get; set; }
        public System.DateTime Дата { get; set; }
    
        public virtual Устройства Устройства { get; set; }
    }
}
