//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smart_Heating_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Устройства
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Устройства()
        {
            this.Статистика = new HashSet<Статистика>();
            this.УстройстваПомещения = new HashSet<УстройстваПомещения>();
        }
    
        public int Id_Устройства { get; set; }
        public string НазваниеУстройства { get; set; }
        public Nullable<int> ВидОтопления { get; set; }
        public string Статус { get; set; }
        public int Температура { get; set; }
        public int КоличествоВоды { get; set; }
        public int КоличествоЭлЭнергии { get; set; }
    
        public virtual Отопление Отопление { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Статистика> Статистика { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<УстройстваПомещения> УстройстваПомещения { get; set; }
    }
}
