//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smart_Heating_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class УстройстваПомещения
    {
        public int ID { get; set; }
        public Nullable<int> Устройство { get; set; }
        public Nullable<int> Id_Помещения { get; set; }
        public Nullable<int> Id_Пользователя { get; set; }
    
        public virtual Пользователь Пользователь { get; set; }
        public virtual Помещение Помещение { get; set; }
        public virtual Устройства Устройства { get; set; }
    }
}
